### PR TITLE
feat(SDLC-41): Create OAuth integration for project

### PR DESCRIPTION
**Pull request by galushka-vitech**
feat(SDLC-41): Create OAuth integration for project

### CODE REVIEW

**Comment by vitech-sdlc** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **oleg-ilechko**
You can assign the PR to them by writing `/assign @oleg-ilechko` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=vitech-team%2Fmood-feed-frontend).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/vitech-team/mood-feed-frontend/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by vitech-sdlc** [comment]
:spider: [ Snyk Container Test Failed ](https://app.snyk.io/org/serhiy-krupka-vitech/project/5a8b3ba2-a003-4d52-82d0-c1f7eb2dc120/history/26e5f9d4-14a1-4225-a9c8-3a8f0ddfe32d
https://snyk.io/plans.) 
 :whale: Image: [gcr.io/sdlc-286111/mood-feed-frontend:0.0.0-SNAPSHOT-PR-57-2]()

**Comment by vitech-sdlc** [comment]
:star: PR built and available in a preview **vitech-team-mood-feed-frontend-pr-57** [here](http://mood-feed-frontend-jx-vitech-team-mood-feed-frontend-pr-57.35.195.151.253.nip.io)

**Review by oleg-ilechko — APPROVED** [review]

**Pull request merged**
